// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBwCcZmIqtGvj7Ow0P-DpChJbIdsmXCu0',
    appId: '1:523647895867:web:86afb26e74300aa37a0f1e',
    messagingSenderId: '523647895867',
    projectId: 'visual-book',
    authDomain: 'visual-book.firebaseapp.com',
    storageBucket: 'visual-book.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJkK7V0BmnYX6cZOiw3-fNogQa-0PznNw',
    appId: '1:523647895867:android:53360e23bd21780a7a0f1e',
    messagingSenderId: '523647895867',
    projectId: 'visual-book',
    storageBucket: 'visual-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYVW0ktmI0Nbe2mVI8ujbjzhA_bzfxEaE',
    appId: '1:523647895867:ios:960ecf343fb6505f7a0f1e',
    messagingSenderId: '523647895867',
    projectId: 'visual-book',
    storageBucket: 'visual-book.appspot.com',
    iosClientId: '523647895867-lq2po26cv8dvcq797sqe0l5kapigher2.apps.googleusercontent.com',
    iosBundleId: 'com.example.visualBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYVW0ktmI0Nbe2mVI8ujbjzhA_bzfxEaE',
    appId: '1:523647895867:ios:f3161a598c8b42e27a0f1e',
    messagingSenderId: '523647895867',
    projectId: 'visual-book',
    storageBucket: 'visual-book.appspot.com',
    iosClientId: '523647895867-sq769iiu9h5d0icjvsbtjgu85ic5gtsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.visualBook.RunnerTests',
  );
}
